name: stack-digital-core
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pillow
  - scikit-image
  - streamlit
  - pip:
    - pycaret[full]
    - pytest
    - nbmake
#prefix: /Users/nick/miniconda3/envs/stack-digital-core
