version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run: 
          name: Install linux compiler 
          command: |
            apt-get update
            apt-get -y install gcc
      - run:
          name: Create conda environment
          command: |
            conda env create -f environment.yml
      - run:
          name: Running tests
          command: |
            source activate stack-digital-core
            python -m pytest -v > artifact.txt
      - store_artifacts:
          path: artifact.txt
          destination: digital-core